# This is workflow name
name: Hello Workflow

on: 
  push:
    branches: main  
    paths: 
      -'**.html'

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: say hello to users
        run: echo "Hello Users"

      - name: say hello to username
        run: echo "Hello $USER "

  details:
    runs-on: ubuntu-latest
    steps:
      - name: say details of Docker and Python
        run: docker --version && python --version
